# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QSizePolicy, QStatusBar, QToolButton,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1012, 1181)
        MainWindow.setProperty(u"centralWidget", u"centralwidget")
        MainWindow.setProperty(u"menuBar", u"menubar")
        MainWindow.setProperty(u"statusBar", u"statusbar")
        self.actionNuevo = QAction(MainWindow)
        self.actionNuevo.setObjectName(u"actionNuevo")
        self.actionSalir = QAction(MainWindow)
        self.actionSalir.setObjectName(u"actionSalir")
        self.actionCargarImagenGeorreferenciar = QAction(MainWindow)
        self.actionCargarImagenGeorreferenciar.setObjectName(u"actionCargarImagenGeorreferenciar")
        self.actionCargarImagenReferencia = QAction(MainWindow)
        self.actionCargarImagenReferencia.setObjectName(u"actionCargarImagenReferencia")
        self.actionGetFromMainScreen = QAction(MainWindow)
        self.actionGetFromMainScreen.setObjectName(u"actionGetFromMainScreen")
        self.actionMetodo1 = QAction(MainWindow)
        self.actionMetodo1.setObjectName(u"actionMetodo1")
        self.actionMetodo2 = QAction(MainWindow)
        self.actionMetodo2.setObjectName(u"actionMetodo2")
        self.actionMetodo3 = QAction(MainWindow)
        self.actionMetodo3.setObjectName(u"actionMetodo3")
        self.actionExportar_img = QAction(MainWindow)
        self.actionExportar_img.setObjectName(u"actionExportar_img")
        self.actionExportar_matrix = QAction(MainWindow)
        self.actionExportar_matrix.setObjectName(u"actionExportar_matrix")
        self.actionimagenortorectificada = QAction(MainWindow)
        self.actionimagenortorectificada.setObjectName(u"actionimagenortorectificada")
        self.actiongroun_control_points = QAction(MainWindow)
        self.actiongroun_control_points.setObjectName(u"actiongroun_control_points")
        self.actionmatrix_transformation = QAction(MainWindow)
        self.actionmatrix_transformation.setObjectName(u"actionmatrix_transformation")
        self.actionImagen_de_referencia = QAction(MainWindow)
        self.actionImagen_de_referencia.setObjectName(u"actionImagen_de_referencia")
        self.actionMDE = QAction(MainWindow)
        self.actionMDE.setObjectName(u"actionMDE")
        self.actioncargar_desde_base_map = QAction(MainWindow)
        self.actioncargar_desde_base_map.setObjectName(u"actioncargar_desde_base_map")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame_image_ortorect = QFrame(self.centralwidget)
        self.frame_image_ortorect.setObjectName(u"frame_image_ortorect")
        self.frame_image_ortorect.setGeometry(QRect(10, 70, 481, 401))
        self.frame_image_ortorect.setFrameShape(QFrame.StyledPanel)
        self.frame_image_ortorect.setFrameShadow(QFrame.Raised)
        self.btnCargarReferencia = QPushButton(self.centralwidget)
        self.btnCargarReferencia.setObjectName(u"btnCargarReferencia")
        self.btnCargarReferencia.setGeometry(QRect(330, 10, 331, 41))
        self.btnCargarFlotante = QPushButton(self.centralwidget)
        self.btnCargarFlotante.setObjectName(u"btnCargarFlotante")
        self.btnCargarFlotante.setGeometry(QRect(20, 10, 301, 41))
        self.img_from_basemap = QPushButton(self.centralwidget)
        self.img_from_basemap.setObjectName(u"img_from_basemap")
        self.img_from_basemap.setGeometry(QRect(670, 10, 331, 41))
        self.frame_imagen_toortorect = QFrame(self.centralwidget)
        self.frame_imagen_toortorect.setObjectName(u"frame_imagen_toortorect")
        self.frame_imagen_toortorect.setGeometry(QRect(520, 70, 481, 401))
        self.frame_imagen_toortorect.setFrameShape(QFrame.StyledPanel)
        self.frame_imagen_toortorect.setFrameShadow(QFrame.Raised)
        self.listWidget = QListWidget(self.centralwidget)
        QListWidgetItem(self.listWidget)
        QListWidgetItem(self.listWidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(10, 580, 171, 71))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(50, 710, 80, 25))
        self.frame_calcs = QFrame(self.centralwidget)
        self.frame_calcs.setObjectName(u"frame_calcs")
        self.frame_calcs.setGeometry(QRect(190, 500, 811, 341))
        self.frame_calcs.setFrameShape(QFrame.StyledPanel)
        self.frame_calcs.setFrameShadow(QFrame.Raised)
        self.toolButton = QToolButton(self.centralwidget)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(140, 710, 24, 24))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 480, 1011, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 870, 1011, 16))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(560, 850, 441, 23))
        self.progressBar.setValue(24)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1012, 24))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        self.menu_EXportar = QMenu(self.menuArchivo)
        self.menu_EXportar.setObjectName(u"menu_EXportar")
        self.menu_Abrir = QMenu(self.menuArchivo)
        self.menu_Abrir.setObjectName(u"menu_Abrir")
        self.menuConfiguracion = QMenu(self.menubar)
        self.menuConfiguracion.setObjectName(u"menuConfiguracion")
        self.menuM_todos = QMenu(self.menuConfiguracion)
        self.menuM_todos.setObjectName(u"menuM_todos")
        self.menuBatch_processing = QMenu(self.menubar)
        self.menuBatch_processing.setObjectName(u"menuBatch_processing")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.menubar.addAction(self.menuBatch_processing.menuAction())
        self.menuArchivo.addAction(self.actionNuevo)
        self.menuArchivo.addAction(self.menu_Abrir.menuAction())
        self.menuArchivo.addAction(self.menu_EXportar.menuAction())
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menu_EXportar.addAction(self.actionimagenortorectificada)
        self.menu_EXportar.addAction(self.actiongroun_control_points)
        self.menu_EXportar.addAction(self.actionmatrix_transformation)
        self.menu_Abrir.addAction(self.actionImagen_de_referencia)
        self.menu_Abrir.addAction(self.actionMDE)
        self.menu_Abrir.addAction(self.actioncargar_desde_base_map)
        self.menuConfiguracion.addSeparator()
        self.menuConfiguracion.addAction(self.menuM_todos.menuAction())
        self.menuM_todos.addSeparator()
        self.menuM_todos.addAction(self.actionMetodo1)
        self.menuM_todos.addAction(self.actionMetodo2)
        self.menuM_todos.addAction(self.actionMetodo3)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Mi Ventana QGIS", None))
        self.actionNuevo.setText(QCoreApplication.translate("MainWindow", u"&Nuevo", None))
#if QT_CONFIG(statustip)
        self.actionNuevo.setStatusTip(QCoreApplication.translate("MainWindow", u"Crear nuevo proyecto", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionNuevo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionSalir.setText(QCoreApplication.translate("MainWindow", u"&Salir", None))
#if QT_CONFIG(statustip)
        self.actionSalir.setStatusTip(QCoreApplication.translate("MainWindow", u"Salir de la aplicaci\u00f3n", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionSalir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionCargarImagenGeorreferenciar.setText(QCoreApplication.translate("MainWindow", u"Cargar imagen a georreferenciar", None))
#if QT_CONFIG(tooltip)
        self.actionCargarImagenGeorreferenciar.setToolTip(QCoreApplication.translate("MainWindow", u"Selecciona la imagen SIN CRS que vas a registrar", None))
#endif // QT_CONFIG(tooltip)
        self.actionCargarImagenReferencia.setText(QCoreApplication.translate("MainWindow", u"Cargar imagen de referencia", None))
#if QT_CONFIG(tooltip)
        self.actionCargarImagenReferencia.setToolTip(QCoreApplication.translate("MainWindow", u"Selecciona la ortofoto/raster con CRS de referencia", None))
#endif // QT_CONFIG(tooltip)
        self.actionGetFromMainScreen.setText(QCoreApplication.translate("MainWindow", u"Capturar desde pantalla", None))
#if QT_CONFIG(tooltip)
        self.actionGetFromMainScreen.setToolTip(QCoreApplication.translate("MainWindow", u"Selecciona un rect\u00e1ngulo en el mapa principal de QGIS y captura la vista", None))
#endif // QT_CONFIG(tooltip)
        self.actionMetodo1.setText(QCoreApplication.translate("MainWindow", u"Metodo1", None))
        self.actionMetodo2.setText(QCoreApplication.translate("MainWindow", u"Metodo2", None))
        self.actionMetodo3.setText(QCoreApplication.translate("MainWindow", u"Metodo3", None))
        self.actionExportar_img.setText(QCoreApplication.translate("MainWindow", u"Exportar img", None))
        self.actionExportar_matrix.setText(QCoreApplication.translate("MainWindow", u"Exportar matrix", None))
        self.actionimagenortorectificada.setText(QCoreApplication.translate("MainWindow", u"imagenortorectificada", None))
        self.actiongroun_control_points.setText(QCoreApplication.translate("MainWindow", u"groun control points", None))
        self.actionmatrix_transformation.setText(QCoreApplication.translate("MainWindow", u"matrix transformation", None))
        self.actionImagen_de_referencia.setText(QCoreApplication.translate("MainWindow", u"Imagen de referencia", None))
        self.actionMDE.setText(QCoreApplication.translate("MainWindow", u"MDE", None))
        self.actioncargar_desde_base_map.setText(QCoreApplication.translate("MainWindow", u"cargar desde base map", None))
        self.btnCargarReferencia.setText(QCoreApplication.translate("MainWindow", u"Cargar imagen a referenciar", None))
        self.btnCargarFlotante.setText(QCoreApplication.translate("MainWindow", u"Cargar Imagen de referencia", None))
        self.img_from_basemap.setText(QCoreApplication.translate("MainWindow", u"Cargar referencia desde base map", None))

        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        ___qlistwidgetitem = self.listWidget.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"Method 1", None));
        ___qlistwidgetitem1 = self.listWidget.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Method 2", None));
        self.listWidget.setSortingEnabled(__sortingEnabled)

        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"get matches", None))
        self.toolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"&Archivo", None))
        self.menu_EXportar.setTitle(QCoreApplication.translate("MainWindow", u"&Exportar", None))
        self.menu_Abrir.setTitle(QCoreApplication.translate("MainWindow", u"&Abrir\u2026", None))
        self.menuConfiguracion.setTitle(QCoreApplication.translate("MainWindow", u"Con&figuraci\u00f3n", None))
        self.menuM_todos.setTitle(QCoreApplication.translate("MainWindow", u"M\u00e9todos", None))
        self.menuBatch_processing.setTitle(QCoreApplication.translate("MainWindow", u"Batch processing", None))
    # retranslateUi

